### ISSUE TITLE
Update needed for 1.20.6

### ISSUE THREAD

**Issue by i1470s** [ItsLewizzz/DeluxeHub#118]
Plugin does not run in current state on 1.20.6 servers.

**Comment by vnkxnzokvmcniomvni** [comment]
Confirmed. All we can do is wait for the update.
![Screenshot 2024-06-16 210415](https://github.com/ItsLewizzz/DeluxeHub/assets/90101465/044940e9-2726-49b6-9a1a-ff81691d1a56)

**Comment by chxseh** [comment]
If you're comfortable downloading jars from strangers, I've compiled a version for 1.20.6 & 1.21.

~~https://git.chse.dev/chase/DeluxeHub/releases~~ https://dl.chse.dev/d?id=hCVu8ITEPXkRnr4

**Comment by TheFaik** [comment]
> If you're comfortable downloading jars from strangers, I've compiled a version for 1.20.6 & 1.21.
> 
> https://git.chse.dev/chase/DeluxeHub/releases

Error occurred while enabling DeluxeHub v3.5.4 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getConfigurationSection(String)" is null
        at DeluxeHub-3.5.4.jar/fun.lewisdev.deluxehub.command.CommandManager.reload(CommandManager.java:42) ~[DeluxeHub-3.5.4.jar:?]
        at DeluxeHub-3.5.4.jar/fun.lewisdev.deluxehub.DeluxeHubPlugin.onEnable(DeluxeHubPlugin.java:84) ~[DeluxeHub-3.5.4.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2246-ad910f8]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2246-ad910f8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[purpur-1.21.jar:1.21-2246-ad910f8]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[purpur-1.21.jar:1.21-2246-ad910f8]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:693) ~[purpur-1.21.jar:1.21-2246-ad910f8]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:455) ~[purpur-1.21.jar:1.21-2246-ad910f8]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:361) ~[purpur-1.21.jar:1.21-2246-ad910f8]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[purpur-1.21.jar:1.21-2246-ad910f8]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2246-ad910f8]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by i1470s** [comment]
> If you're comfortable downloading jars from strangers, I've compiled a version for 1.20.6 & 1.21.
> 
> https://git.chse.dev/chase/DeluxeHub/releases

Thank you very much! works great!

**Comment by SliderKP** [comment]
> If you're comfortable downloading jars from strangers, I've compiled a version for 1.20.6 & 1.21.
> 
> https://git.chse.dev/chase/DeluxeHub/releases

thanks for updating !!

**Comment by ZombyWarrior** [comment]
> If you're comfortable downloading jars from strangers, I've compiled a version for 1.20.6 & 1.21.
> 
> https://git.chse.dev/chase/DeluxeHub/releases

is there a tutorial out there to do this with other plugins?

**Comment by chxseh** [comment]
> is there a tutorial out there to do this with other plugins?

https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/

**Comment by ResumaMC** [comment]
> > is there a tutorial out there to do this with other plugins?
> 
> https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/

Hey, can you make an update for 1.21.3? It would also mean a lot to me if you teach me how to update it myself afterwards.
