### ISSUE TITLE
Bug. 

### ISSUE THREAD

**Issue by Porkason** [ItsLewizzz/DeluxeHub#17]
>.... [20:47:47 WARN]: [DeluxeHub] Task #3201 for DeluxeHub v3.3.9 generated an exception
java.lang.NullPointerException: null
at fun.lewisdev.deluxehub.action.ActionManager.lambda$executeActions$1(ActionManager.java:49) ~[?:?]
at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
at fun.lewisdev.deluxehub.action.ActionManager.executeActions(ActionManager.java:47) ~[?:?]
at fun.lewisdev.deluxehub.module.Module.executeActions(Module.java:60) ~[?:?]
at fun.lewisdev.deluxehub.module.modules.player.PlayerListener.lambda$onPlayerJoin$1(PlayerListener.java:113) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-253]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.3.jar:git-Paper-253]
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.3.jar:git-Paper-253]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-253]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-253]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-253]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-253]
at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by ItsLewizzz** [comment]
One of your actions are incorrectly configured under the join actions in the configuration. This is not a bug.
