### ISSUE TITLE
Error in UUID remove player for tablist

### ISSUE THREAD

**Issue by axel578** [ItsLewizzz/DeluxeHub#3]
I constantly get this error which make the player crash : 
java.util.ConcurrentModificationException: null
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_241]
	at fun.lewisdev.deluxehub.module.modules.visual.tablist.TablistUpdateTask.run(TablistUpdateTask.java:13) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [server.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [server.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:399) [server.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [server.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [server.jar:git-Spigot-800b93f-8160e29]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

the bug seems to come from there : https://github.com/ItsLewizzz/DeluxeHub/blob/77ad3f402205b3680d7a66db3fea69d182263b6f/src/main/java/fun/lewisdev/deluxehub/module/modules/visual/tablist/TablistUpdateTask.java

I am on spigot server minecraft 1.15.2

**Comment by ItsLewizzz** [comment]
What version of DeluxeHub are you using?

**Comment by Andrei12333** [comment]
I think he is using the latest deluxehub version that works on with the minecraft server version "Spigot 1.15.2"
