### ISSUE TITLE
NBTAPI Struggles finding NMS support

### ISSUE THREAD

**Issue by CubicFace** [ItsLewizzz/DeluxeHub#4]
Everytime I start the server I get this error, which screws up the plugin.
Here is the logs
```log
[15:39:38 INFO]: [DeluxeHub] Enabling DeluxeHub v3.3.0
[15:39:38 INFO]: [DeluxeHub]  _   _            _          _    _ 
15:39:38 INFO]: [DeluxeHub] | \ |_ |  | | \/ |_ |_| | | |_)   _)                                                       
[15:39:38 INFO]: [DeluxeHub] |_/ |_ |_ |_| /\ |_ | | |_| |_)   _)                                                       
[15:39:38 INFO]: [DeluxeHub]                                                                                            
[15:39:38 INFO]: [DeluxeHub] Version: 3.3.0                                                                             
[15:39:38 INFO]: [DeluxeHub] Author: ItsLewizzz                                                                         
[15:39:38 INFO]: [DeluxeHub]                                                                                            
[15:39:38 INFO]: [DeluxeHub]  Hooked into PlaceholderAPI                                                                
[15:39:38 INFO]: [DeluxeHub] Loaded custom menu 'serverselector'.
[15:39:38 INFO]: [NBTAPI] Found Spigot: v1_8_R2! Trying to find NMS support
[15:39:38 WARN]: [NBTAPI] Wasn't able to find NMS Support! Some functions may not work!
[15:39:38 WARN]: fun.lewisdev.deluxehub.libs.nbtapi.NbtApiException: Method not loaded! 'ITEMSTACK_NMSCOPY'             [15:39:38 WARN]:        at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:149)                                                                                                                 
[15:39:38 WARN]:        at fun.lewisdev.deluxehub.libs.nbtapi.NBTItem.getCompound(NBTItem.java:34)                      
[15:39:38 WARN]:        at fun.lewisdev.deluxehub.libs.nbtapi.NBTReflectionUtil.setData(NBTReflectionUtil.java:503)     
[15:39:38 WARN]:        at fun.lewisdev.deluxehub.libs.nbtapi.NBTCompound.setString(NBTCompound.java:77)                
[15:39:38 WARN]:        at fun.lewisdev.deluxehub.module.modules.hotbar.HotbarItem.<init>(HotbarItem.java:35)           [15:39:38 WARN]:        at fun.lewisdev.deluxehub.module.modules.hotbar.items.CustomItem.<init>(CustomItem.java:16)     
[15:39:38 WARN]:        at fun.lewisdev.deluxehub.module.modules.hotbar.HotbarManager.onEnable(HotbarManager.java:34)   
[15:39:38 WARN]:        at fun.lewisdev.deluxehub.module.ModuleManager.loadModules(ModuleManager.java:66)               
[15:39:38 WARN]:        at fun.lewisdev.deluxehub.DeluxeHub.onEnable(DeluxeHub.java:90)                                 
[15:39:38 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)                            
[15:39:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)              
[15:39:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)             
[15:39:38 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356)                  
[15:39:38 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316)               
[15:39:38 WARN]:        at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416)                     
[15:39:38 WARN]:        at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382)                     
[15:39:38 WARN]:        at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337)                     
[15:39:38 WARN]:        at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257)                  
[15:39:38 WARN]:        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522)                   
[15:39:38 WARN]:        at java.lang.Thread.run(Unknown Source)                                                         
[15:39:38 ERROR]: [DeluxeHub] ============= DELUXEHUB MODULE LOAD ERROR =============                                   
[15:39:38 ERROR]: [DeluxeHub] There was an error loading the HOTBAR_ITEMS module                                        
[15:39:38 ERROR]: [DeluxeHub] The plugin will now disable..                                                             
[15:39:38 ERROR]: [DeluxeHub] ============= DELUXEHUB MODULE LOAD ERROR =============                                   
[15:39:38 INFO]: [DeluxeHub] Disabling DeluxeHub v3.3.0                                                                 
[15:39:38 INFO]: [DeluxeHub] Loaded 16 plugin modules.                                                                  
[15:39:38 INFO]: [DeluxeHub]                                                                                            
[15:39:38 INFO]: [DeluxeHub] Successfully loaded in 139ms
```
What can I do?

**Comment by ItsLewizzz** [comment]
You need to upgrade to Spigot 1.8.8
