### ISSUE TITLE
[BUG] 1.18.2 release

### ISSUE THREAD

**Issue by jonaas13** [ItsLewizzz/DeluxeHub#46]
Current version does not work on 1.18.2

**Comment by ItsLewizzz** [comment]
I need more information such as any errors.

**Comment by jonaas13** [comment]
`[22:37:22] [Server thread/INFO]: [DeluxeHub] Enabling DeluxeHub v3.5.0
[22:37:22] [Server thread/INFO]: [DeluxeHub]  _   _            _          _    _ 
[22:37:22] [Server thread/INFO]: [DeluxeHub] | \ |_ |  | | \/ |_ |_| | | |_)   _)
[22:37:22] [Server thread/INFO]: [DeluxeHub] |_/ |_ |_ |_| /\ |_ | | |_| |_)   _)
[22:37:22] [Server thread/INFO]: [DeluxeHub] 
[22:37:22] [Server thread/INFO]: [DeluxeHub] Version: 3.5.0
[22:37:22] [Server thread/INFO]: [DeluxeHub] Author: ItsLewizzz
[22:37:22] [Server thread/INFO]: [DeluxeHub] 
[22:37:22] [Server thread/INFO]: [DeluxeHub]  Hooked into PlaceholderAPI
[22:37:22] [Server thread/INFO]: [DeluxeHub] Loaded custom menu 'serverselector'.
[22:37:22] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_18_R2! Trying to find NMS support
[22:37:22] [Server thread/WARN]: [NBTAPI] [NBTAPI] Wasn't able to find NMS Support! Some functions may not work!
[22:37:22] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[22:37:22] [Server thread/WARN]: [NBTAPI] [NBTAPI] Error while trying to resolve the class 'inventory.CraftItemStack'!
java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.inventory.CraftItemStack
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:75) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:55) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ClassWrapper.<clinit>(ClassWrapper.java:17) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ReflectionMethod.<clinit>(ReflectionMethod.java:23) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.NBTCompound.setString(NBTCompound.java:102) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.modules.hotbar.HotbarItem.<init>(HotbarItem.java:37) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.modules.hotbar.items.CustomItem.<init>(CustomItem.java:16) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.modules.hotbar.HotbarManager.onEnable(HotbarManager.java:34) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.ModuleManager.loadModules(ModuleManager.java:73) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.DeluxeHubPlugin.onEnable(DeluxeHubPlugin.java:95) ~[DeluxeHub-3.5.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1172) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:37:22] [Server thread/WARN]: [NBTAPI] [NBTAPI] Error while trying to resolve the class 'inventory.CraftMetaItem'!
java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.inventory.CraftMetaItem
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:75) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:55) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ClassWrapper.<clinit>(ClassWrapper.java:18) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ReflectionMethod.<clinit>(ReflectionMethod.java:23) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.NBTCompound.setString(NBTCompound.java:102) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.modules.hotbar.HotbarItem.<init>(HotbarItem.java:37) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.modules.hotbar.items.CustomItem.<init>(CustomItem.java:16) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.modules.hotbar.HotbarManager.onEnable(HotbarManager.java:34) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.ModuleManager.loadModules(ModuleManager.java:73) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.DeluxeHubPlugin.onEnable(DeluxeHubPlugin.java:95) ~[DeluxeHub-3.5.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1172) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:37:22] [Server thread/WARN]: [NBTAPI] [NBTAPI] Error while trying to resolve the class 'entity.CraftEntity'!
java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.entity.CraftEntity
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:75) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:55) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ClassWrapper.<clinit>(ClassWrapper.java:19) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ReflectionMethod.<clinit>(ReflectionMethod.java:23) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.NBTCompound.setString(NBTCompound.java:102) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.modules.hotbar.HotbarItem.<init>(HotbarItem.java:37) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.modules.hotbar.items.CustomItem.<init>(CustomItem.java:16) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.modules.hotbar.HotbarManager.onEnable(HotbarManager.java:34) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.ModuleManager.loadModules(ModuleManager.java:73) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.DeluxeHubPlugin.onEnable(DeluxeHubPlugin.java:95) ~[DeluxeHub-3.5.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1172) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:37:22] [Server thread/WARN]: [NBTAPI] [NBTAPI] Error while trying to resolve the class 'CraftWorld'!
java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.CraftWorld
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:75) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:55) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ClassWrapper.<clinit>(ClassWrapper.java:20) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ReflectionMethod.<clinit>(ReflectionMethod.java:23) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.NBTCompound.setString(NBTCompound.java:102) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.modules.hotbar.HotbarItem.<init>(HotbarItem.java:37) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.modules.hotbar.items.CustomItem.<init>(CustomItem.java:16) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.modules.hotbar.HotbarManager.onEnable(HotbarManager.java:34) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.ModuleManager.loadModules(ModuleManager.java:73) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.DeluxeHubPlugin.onEnable(DeluxeHubPlugin.java:95) ~[DeluxeHub-3.5.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1172) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:37:22] [Server thread/WARN]: [NBTAPI] [NBTAPI] Error while trying to resolve the class 'persistence.CraftPersistentDataContainer'!
java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.persistence.CraftPersistentDataContainer
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:75) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:55) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ClassWrapper.<clinit>(ClassWrapper.java:21) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ReflectionMethod.<clinit>(ReflectionMethod.java:23) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.libs.nbtapi.NBTCompound.setString(NBTCompound.java:102) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.modules.hotbar.HotbarItem.<init>(HotbarItem.java:37) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.modules.hotbar.items.CustomItem.<init>(CustomItem.java:16) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.modules.hotbar.HotbarManager.onEnable(HotbarManager.java:34) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.ModuleManager.loadModules(ModuleManager.java:73) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.DeluxeHubPlugin.onEnable(DeluxeHubPlugin.java:95) ~[DeluxeHub-3.5.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1172) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:37:22] [Server thread/INFO]: [DeluxeHub] [NBTAPI] Unable to find the method 'asNMSCopy' in 'null' Args: [class org.bukkit.inventory.ItemStack] Enum: ITEMSTACK_NMSCOPY
[22:37:22] [Server thread/INFO]: [DeluxeHub] [NBTAPI] Unable to find the method 'asCraftMirror' in 'null' Args: [class net.minecraft.world.item.ItemStack] Enum: ITEMSTACK_BUKKITMIRROR
[22:37:22] [Server thread/INFO]: [DeluxeHub] [NBTAPI] Unable to find the method 'getHandle' in 'null' Args: [] Enum: CRAFT_WORLD_GET_HANDLE
[22:37:22] [Server thread/INFO]: [DeluxeHub] [NBTAPI] Unable to find the method 'getHandle' in 'null' Args: [] Enum: CRAFT_ENTITY_GET_HANDLE
[22:37:22] [Server thread/INFO]: [DeluxeHub] [NBTAPI] Unable to find the method 'toTagCompound' in 'null' Args: [] Enum: CRAFT_PERSISTENT_DATA_CONTAINER_TO_TAG
[22:37:22] [Server thread/INFO]: [DeluxeHub] [NBTAPI] Unable to find the method 'getRaw' in 'null' Args: [] Enum: CRAFT_PERSISTENT_DATA_CONTAINER_GET_MAP
[22:37:22] [Server thread/INFO]: [DeluxeHub] [NBTAPI] Unable to find the method 'putAll' in 'null' Args: [class net.minecraft.nbt.NBTTagCompound] Enum: CRAFT_PERSISTENT_DATA_CONTAINER_PUT_ALL
[22:37:22] [Server thread/ERROR]: Error occurred while enabling DeluxeHub v3.5.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at fun.lewisdev.deluxehub.libs.nbtapi.NBTCompound.setString(NBTCompound.java:102) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.modules.hotbar.HotbarItem.<init>(HotbarItem.java:37) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.modules.hotbar.items.CustomItem.<init>(CustomItem.java:16) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.modules.hotbar.HotbarManager.onEnable(HotbarManager.java:34) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.module.ModuleManager.loadModules(ModuleManager.java:73) ~[DeluxeHub-3.5.0.jar:?]
	at fun.lewisdev.deluxehub.DeluxeHubPlugin.onEnable(DeluxeHubPlugin.java:95) ~[DeluxeHub-3.5.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1172) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1574]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getDeclaredField(String)" because the return value of "fun.lewisdev.deluxehub.libs.nbtapi.utils.nmsmappings.ClassWrapper.getClazz()" is null
	at fun.lewisdev.deluxehub.libs.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:35) ~[DeluxeHub-3.5.0.jar:?]
	... 17 more
[22:37:22] [Server thread/INFO]: [DeluxeHub] Disabling DeluxeHub v3.5.0
[22:37:22] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.util.List.clear()" because "this.vanished" is null
[22:37:22] [Server thread/WARN]: 	at DeluxeHub-3.5.0.jar//fun.lewisdev.deluxehub.module.modules.player.PlayerVanish.onDisable(PlayerVanish.java:34)
[22:37:22] [Server thread/WARN]: 	at DeluxeHub-3.5.0.jar//fun.lewisdev.deluxehub.module.ModuleManager.unloadModules(ModuleManager.java:92)
[22:37:22] [Server thread/WARN]: 	at DeluxeHub-3.5.0.jar//fun.lewisdev.deluxehub.DeluxeHubPlugin.onDisable(DeluxeHubPlugin.java:113)
[22:37:22] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[22:37:22] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401)
[22:37:22] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538)
[22:37:22] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376)
[22:37:22] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[22:37:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[22:37:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[22:37:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671)
[22:37:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438)
[22:37:22] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:352)
[22:37:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1172)
[22:37:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[22:37:22] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[22:37:22] [Server thread/ERROR]: [DeluxeHub] There was an error unloading the VANISH module.
[22:37:22] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.util.Set.forEach(java.util.function.Consumer)" because "this.holograms" is null
[22:37:22] [Server thread/WARN]: 	at DeluxeHub-3.5.0.jar//fun.lewisdev.deluxehub.module.modules.hologram.HologramManager.saveHolograms(HologramManager.java:61)
[22:37:22] [Server thread/WARN]: 	at DeluxeHub-3.5.0.jar//fun.lewisdev.deluxehub.module.modules.hologram.HologramManager.onDisable(HologramManager.java:36)
[22:37:22] [Server thread/WARN]: 	at DeluxeHub-3.5.0.jar//fun.lewisdev.deluxehub.module.ModuleManager.unloadModules(ModuleManager.java:92)
[22:37:22] [Server thread/WARN]: 	at DeluxeHub-3.5.0.jar//fun.lewisdev.deluxehub.DeluxeHubPlugin.onDisable(DeluxeHubPlugin.java:113)
[22:37:22] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[22:37:22] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401)
[22:37:22] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538)
[22:37:22] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376)
[22:37:22] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[22:37:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[22:37:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[22:37:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671)
[22:37:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438)
[22:37:22] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:352)
[22:37:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1172)
[22:37:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[22:37:22] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[22:37:22] [Server thread/ERROR]: [DeluxeHub] There was an error unloading the HOLOGRAMS module.`

**Comment by jonaas13** [comment]
Holographic Displays is also not working on 1.18.2, not sure if it's needed for dependencies.

**Comment by ItsLewizzz** [comment]
HolographicDisplays issue would be separate. I’ll push a DeluxeHub update shortly to solve these errors.

**Comment by ItsLewizzz** [comment]
Please use v3.5.1. This issue has been resolved.
