### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by TeamRaZeR** [ItsLewizzz/DeluxeHub#54]
[14:09:47 WARN]: [DeluxeHub] Task #13084 for DeluxeHub v3.5.2 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
        at fun.lewisdev.deluxehub.action.actions.TitleAction.execute(TitleAction.java:30) ~[DeluxeHub-3.5.2.jar:?]
        at fun.lewisdev.deluxehub.action.ActionManager.lambda$executeActions$1(ActionManager.java:55) ~[DeluxeHub-3.5.2.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at fun.lewisdev.deluxehub.action.ActionManager.executeActions(ActionManager.java:47) ~[DeluxeHub-3.5.2.jar:?]
        at fun.lewisdev.deluxehub.module.Module.executeActions(Module.java:60) ~[DeluxeHub-3.5.2.jar:?]
        at fun.lewisdev.deluxehub.module.modules.player.PlayerListener.lambda$onPlayerJoin$1(PlayerListener.java:113) ~[DeluxeHub-3.5.2.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-61]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-61]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by TeamRaZeR** [comment]
First time I see this error
I've never had it before

**Comment by SnowSakuraKo** [comment]
I have the same problem, so the title won't show while joining the server.

**Comment by SnowSakuraKo** [comment]
Oh Okay, I got the solution.
The '[TITLE]' line, you need to provide all five parameters.

![Image](https://github.com/user-attachments/assets/c2551342-cebf-4c34-8a87-0a74f6b54824)
