### ISSUE TITLE
PrepareItemCraft event may only be triggered synchronously

### ISSUE THREAD

**Issue by Dagrond** [ItsLewizzz/DeluxeHub#55]
My lobby console is getting spammed with this:
`
[12:19:33 WARN]: [DeluxeHub] Plugin DeluxeHub v3.5.2 generated an exception while executing task 23
java.lang.IllegalStateException: PrepareItemCraftEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:659) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1388) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at net.minecraft.world.inventory.CraftingMenu.slotChangedCraftingGrid(CraftingMenu.java:87) ~[?:?]
        at net.minecraft.world.inventory.InventoryMenu.slotsChanged(InventoryMenu.java:142) ~[?:?]
        at net.minecraft.world.inventory.CraftingContainer.setItem(CraftingContainer.java:141) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftInventoryCrafting.setItem(CraftInventoryCrafting.java:79) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at fun.lewisdev.deluxehub.inventory.AbstractInventory.refreshInventory(AbstractInventory.java:51) ~[DeluxeHub-3.5.2.jar:?]
        at fun.lewisdev.deluxehub.inventory.InventoryTask.run(InventoryTask.java:21) ~[DeluxeHub-3.5.2.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

Using DeluxeHub 3.5.2, this was happening also on 3.5.1.

**Comment by Amirali1059** [comment]
I'm having the same issues on 1.20.1 paper using DeluxeHub 3.5.5
